//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public long AnnouncementID { get; set; }
        public string TitleTxt { get; set; }
        public string ImageURLTxt { get; set; }
        public string AltImageTxt { get; set; }
        public string DescriptionTxt { get; set; }
        public Nullable<System.DateTime> ScheduleDateTime { get; set; }
        public Nullable<System.DateTime> DisplayStartDate { get; set; }
        public Nullable<System.DateTime> DisplayEndDate { get; set; }
        public Nullable<bool> StatusInd { get; set; }
        public Nullable<long> DisplayOrderNbr { get; set; }
        public Nullable<System.DateTime> AnnouncementCreateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateByID { get; set; }
        public Nullable<long> LastModifyByID { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public Nullable<bool> IsDeletedInd { get; set; }
        public Nullable<long> TypeMasterID { get; set; }
        public string ScheduleTimeTxt { get; set; }
    
        public virtual TypeMaster TypeMaster { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
