//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormEmail
    {
        public int FormEmailID { get; set; }
        public long EmailID { get; set; }
        public long EmailTypeID { get; set; }
        public long ContentTypeID { get; set; }
    
        public virtual ContentType ContentType { get; set; }
        public virtual Email Email { get; set; }
        public virtual EmailType EmailType { get; set; }
    }
}
