//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingParameter
    {
        public int ListingParameterID { get; set; }
        public string ListingParameterTxt { get; set; }
        public string DescriptionTxt { get; set; }
    }
}
