//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.DepartmentStaffs = new HashSet<DepartmentStaff>();
        }
    
        public long StaffID { get; set; }
        public string FirstNameTxt { get; set; }
        public string LastNameTxt { get; set; }
        public string DesignationTxt { get; set; }
        public Nullable<long> SchoolCategoryID { get; set; }
        public Nullable<long> SchoolID { get; set; }
        public string PhoneTxt { get; set; }
        public string EmailTxt { get; set; }
        public Nullable<long> DisplayOrderNbr { get; set; }
        public Nullable<bool> StatusInd { get; set; }
        public Nullable<System.DateTime> StaffCreateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateByID { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public Nullable<long> LastModifyByID { get; set; }
        public Nullable<bool> IsDeletedInd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentStaff> DepartmentStaffs { get; set; }
        public virtual School School { get; set; }
        public virtual School School1 { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
