//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemChangeLogDetail
    {
        public long ChangeLogDetailID { get; set; }
        public long ChangeLogID { get; set; }
        public string FieldNameTxt { get; set; }
        public string OldValueTxt { get; set; }
        public string NewValueTxt { get; set; }
    
        public virtual SystemChangeLog SystemChangeLog { get; set; }
    }
}
