//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Content()
        {
            this.Content1 = new HashSet<Content>();
        }
    
        public long ContentID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public long ContentTypeID { get; set; }
        public bool IsExternalLinkInd { get; set; }
        public string ExternalLinkTxt { get; set; }
        public bool ExternalLinkTargetInd { get; set; }
        public string PageTitleTxt { get; set; }
        public string MenuTitleTxt { get; set; }
        public string PageURLTxt { get; set; }
        public string AbstractTxt { get; set; }
        public string DescriptionTxt { get; set; }
        public Nullable<long> DisplayOrderNbr { get; set; }
        public Nullable<long> BannerImageID { get; set; }
        public string AltBannerImageTxt { get; set; }
        public string BannerImageAbstractTxt { get; set; }
        public bool StatusInd { get; set; }
        public string PageMetaTitleTxt { get; set; }
        public string PageMetaDescriptionTxt { get; set; }
        public string RightSectionTitleTxt { get; set; }
        public string RightSectionAbstractTxt { get; set; }
        public Nullable<System.DateTime> ContentCreateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateByID { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public Nullable<long> LastModifyByID { get; set; }
        public Nullable<bool> IsDeletedInd { get; set; }
        public Nullable<bool> IsFacebookSharingInd { get; set; }
        public Nullable<bool> IsTwitterSharingInd { get; set; }
        public Nullable<bool> IsGooglePlusSharingInd { get; set; }
        public Nullable<long> DepartmentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Content1 { get; set; }
        public virtual Content Content2 { get; set; }
        public virtual ContentType ContentType { get; set; }
        public virtual Image Image { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
