//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Department1 = new HashSet<Department>();
            this.DepartmentStaffs = new HashSet<DepartmentStaff>();
        }
    
        public long DepartmentID { get; set; }
        public string NameTxt { get; set; }
        public string URLTxt { get; set; }
        public string RightSectionTitleTxt { get; set; }
        public string RightSectionAbstractTxt { get; set; }
        public string AddressTxt { get; set; }
        public string PhoneNumberTxt { get; set; }
        public string FaxNumberTxt { get; set; }
        public string DescriptionTxt { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<long> DisplayOrderNbr { get; set; }
        public Nullable<bool> StatusInd { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateByID { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public Nullable<long> LastModifyByID { get; set; }
        public string PageMetaTitleTxt { get; set; }
        public string PageMetaDescription { get; set; }
        public Nullable<bool> IsDeletedInd { get; set; }
        public Nullable<System.DateTime> DepartmentCreateDate { get; set; }
        public Nullable<long> BannerImageID { get; set; }
        public string AltBannerImageTxt { get; set; }
        public string BannerImageAbstractTxt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Department1 { get; set; }
        public virtual Department Department2 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentStaff> DepartmentStaffs { get; set; }
    }
}
