//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Image()
        {
            this.Contents = new HashSet<Content>();
            this.ExceptionOpportunities = new HashSet<ExceptionOpportunity>();
            this.RightSections = new HashSet<RightSection>();
        }
    
        public long ImageID { get; set; }
        public long ImageTypeID { get; set; }
        public string ImgPathTxt { get; set; }
        public string TitleTxt { get; set; }
        public string AltImageTxt { get; set; }
        public string URLTxt { get; set; }
        public Nullable<bool> TargetWindowInd { get; set; }
        public Nullable<System.DateTime> DisplayStartDate { get; set; }
        public Nullable<System.DateTime> DisplayEndDate { get; set; }
        public string AbstractTxt { get; set; }
        public Nullable<long> DisplayOrderNbr { get; set; }
        public bool StatusInd { get; set; }
        public Nullable<System.DateTime> ImageCreateDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> CreateByID { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public Nullable<long> LastModifyByID { get; set; }
        public Nullable<bool> IsDeletedInd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Contents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionOpportunity> ExceptionOpportunities { get; set; }
        public virtual ImageType ImageType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RightSection> RightSections { get; set; }
    }
}
