//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RightSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RightSection()
        {
            this.RightSection1 = new HashSet<RightSection>();
        }
    
        public long RightSectionID { get; set; }
        public Nullable<bool> IsParentTitleInd { get; set; }
        public string TitleTxt { get; set; }
        public string PageTitleTxt { get; set; }
        public string RightSectionTitleTxt { get; set; }
        public string RightSectionAbstractTxt { get; set; }
        public string DescriptionTxt { get; set; }
        public Nullable<bool> IsExternalLinkInd { get; set; }
        public string ExternalLinkURLTxt { get; set; }
        public Nullable<bool> ExternalLinkTargetInd { get; set; }
        public Nullable<bool> StatusInd { get; set; }
        public Nullable<long> BannerImageID { get; set; }
        public string AltBannerImageTxt { get; set; }
        public string BannerImageAbstractTxt { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<System.DateTime> RightSectionCreateDate { get; set; }
        public string PageMetaTitleTxt { get; set; }
        public string PageMetaDescriptionTxt { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreatedByID { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public Nullable<long> LastModifyByID { get; set; }
        public Nullable<bool> IsDeletedInd { get; set; }
        public string TableNameTxt { get; set; }
        public Nullable<long> ListingID { get; set; }
        public Nullable<long> TypeMasterID { get; set; }
        public Nullable<bool> IsFacebookSharingInd { get; set; }
        public Nullable<bool> IsTwitterSharingInd { get; set; }
        public Nullable<bool> IsGooglePlusSharingInd { get; set; }
    
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RightSection> RightSection1 { get; set; }
        public virtual RightSection RightSection2 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
