//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School()
        {
            this.ExceptionOpportunities = new HashSet<ExceptionOpportunity>();
            this.Staffs = new HashSet<Staff>();
            this.Staffs1 = new HashSet<Staff>();
        }
    
        public long SchoolID { get; set; }
        public Nullable<long> SchoolCategoryID { get; set; }
        public string NameTxt { get; set; }
        public string AddressTxt { get; set; }
        public string PhoneNumberTxt { get; set; }
        public string WebsiteURLTxt { get; set; }
        public Nullable<bool> StatusInd { get; set; }
        public Nullable<System.DateTime> SchoolCreateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateByID { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public Nullable<long> LastModifyByID { get; set; }
        public Nullable<bool> IsDeletedInd { get; set; }
        public Nullable<long> TypeMasterID { get; set; }
        public string PageURLTxt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionOpportunity> ExceptionOpportunities { get; set; }
        public virtual TypeMaster TypeMaster { get; set; }
        public virtual TypeMaster TypeMaster1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staffs1 { get; set; }
    }
}
