//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemAccessLog
    {
        public long SystemAccessLogID { get; set; }
        public string NameTxt { get; set; }
        public string UserNameTxt { get; set; }
        public Nullable<short> UserRoleID { get; set; }
        public Nullable<System.DateTime> LoginDateTime { get; set; }
        public Nullable<System.DateTime> LogoutDateTime { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
