//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemChangeLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemChangeLog()
        {
            this.SystemChangeLogDetails = new HashSet<SystemChangeLogDetail>();
        }
    
        public long ChangeLogID { get; set; }
        public string NameTxt { get; set; }
        public string UsernameTxt { get; set; }
        public Nullable<short> UserRoleID { get; set; }
        public string ModuleTxt { get; set; }
        public string LogTypeTxt { get; set; }
        public string NotesTxt { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemChangeLogDetail> SystemChangeLogDetails { get; set; }
    }
}
