//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISD
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDepartment
    {
        public long UserDepartmentID { get; set; }
        public long UserID { get; set; }
        public long DepartmentID { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
